In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("C:/Users/Ibscai22/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          NaN           1.4          0.2  Iris-setosa

In [9]:
df.isnull()

    sepal_length  sepal_width  petal_length  petal_width  class
0          False        False         False        False  False
1          False        False         False        False  False
2          False        False         False        False  False
3          False        False         False        False  False
4          False         True         False        False  False
..           ...          ...           ...          ...    ...
79         False        False         False        False  False
80         False        False         False        False  False
81         False        False         False        False  False
82          True        False         False        False  False
83         False        False          True         True  False

[84 rows x 5 columns]

In [10]:
df.isnull().sum()

sepal_length    4
sepal_width     5
petal_length    4
petal_width     4
class           1
dtype: int64

In [16]:
df['sepal_length']=df['sepal_length'].fillna(7)

In [17]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    4
petal_width     4
class           1
dtype: int64

In [18]:
mn=df['sepal_width'].mean()
mn

np.float64(3.1430379746835437)

In [19]:
df['sepal_width']=df['sepal_width'].fillna(mn)

In [20]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    4
petal_width     4
class           1
dtype: int64

In [22]:
med=df['petal_length'].median()
med

1.6

In [23]:
df['petal_length']=df['petal_length'].fillna(med)

In [24]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     4
class           1
dtype: int64

In [28]:
mod=df['petal_width'].mode()[0]
mod

np.float64(0.2)

In [29]:
df['petal_width']=df['petal_width'].fillna(mod)

In [30]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           1
dtype: int64

In [33]:
df['petal_width']=df['petal_width'].ffill()
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [34]:
df['class']=df['class'].bfill()
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64